version: "3.1"

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: deployer-node
    image: rebelinblue/deployer-node:latest
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/node/supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - "6001:6001"
    links:
      - redis
    networks:
      - deployer

  beanstalkd:
    image: schickling/beanstalkd
    container_name: deployer-beanstalkd
    networks:
      - deployer

  mailhog:
    image: phpdockerio/mailhog:latest
    container_name: deployer-mailhog
    ports:
      - "8001:8025"
    networks:
      - deployer

  redis:
    image: phpdockerio/redis:latest
    container_name: deployer-redis
    networks:
      - deployer

  mysql:
    image: mysql:5.7
    container_name: deployer-mysql
    working_dir: /application
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=deployer
      - MYSQL_USER=deployer
      - MYSQL_PASSWORD=secret
    volumes:
      - data:/var/lib/mysql
    networks:
      - deployer

  nginx:
    image: phpdockerio/nginx:latest
    container_name: deployer-nginx
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - php-fpm
      - node
    networks:
      - deployer

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: deployer-worker
    image: rebelinblue/deployer-worker:latest
    volumes:
      - .:/application
      - ./docker/worker/supervisord.conf:/etc/supervisord.conf
    links:
      - beanstalkd
      - mysql
      - redis
    networks:
      - deployer

  composer:
    build:
      context: .
      dockerfile: docker/composer/Dockerfile
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    image: composer:latest
    container_name: deployer-composer
    volumes:
      - .:/application
    links:
      - mysql
    networks:
      - deployer

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=deployer"
      COMPOSER_ALLOW_SUPERUSER: 1
    container_name: deployer-php-fpm
    image: rebelinblue/deployer-php-fpm:latest
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    links:
      - beanstalkd
      - mailhog
      - mysql
      - redis
    networks:
      - deployer

volumes:
  data:
    driver: "local"

networks:
  deployer:
    driver: bridge
